server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
  port: 8082

spring:
  application:
    name: projectBase

  datasource:
    url: jdbc:h2:mem:projectBase;DB_CLOSE_DELAY=-1;
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true